### ISSUE TITLE
Does this plugin actually work??

### ISSUE THREAD

**Issue by cronoklee** [icetee/remote-ftp#1037]
Atom v1.21.1
remote-ftp: v1.2.6
Windows 10

I've just discovered atom and it looks amazing but without FTP its useless to me. I have tried all the FTP packages available (all bad). This one seems to be the one everyone uses and is the closest to a sensible workflow but I've spent several hours now trying to get it working using FTP and SFTP without success.  Bugs in ftp are totally unacceptable even for only semi-professional projects. You just cannot have FTP behaving unpredictably. I really can't understand why FTP is not part of the Atom core packages? 

Issues I've found with remote-ftp:
**Upload**
Shows notification  "Remote FTP: All transfers succeeded (1 of 1)" but the file has not actually changed on the server. Clicking download again immediately afterwards overwrites my changes with the old server version.

**Sync local - remote**
Same as upload

**Download**
This command just downloads a load of random files and directories/sub-directories from the server into my project making a gigantic mess. What the actual fuck.

**Prompts**
There are no prompts or notifications when changes may be overwritten. Professional FTP package should prompt when:
- A local file has been edited and is going to be overwritten with a server version.
- A server file has been edited since last download and is going to be overwritten with a local version.

**Toggle** 
Does not actually show the window. It makes a hidden arrow on the left hand side which I can then find by hovering and then click to show the remote window.

**Comment by icetee** [comment]
**Sync local - remote**
Unfortunately, now there is no reason for sync remote command.
Accordingly, the download method itself will be a problem! 😢

I've been trying to implement these recommendations. But 99% of servers do not support a hash commands. It is therefore difficult to check the status of the files. The date is not worth much in itself because of the client and server connection. The date of files will never be the same.

I delete all files in local before I begin working on the project. All files open in the server (double click) and the save file upload always. I do not have much time for development that I can always do.

**Comment by btstw** [comment]
@cronoklee 
Toggle issue seems to be atom setting, got to themes > UI themes > gear box > checked Hide dock toggle button, enable this so that dock no longer hide automatically.
some themes didn't have gear box button, it is themes plugin problem, not remote-ftp plugin.

**Comment by asturur** [comment]
I m on atom 1.22-beta1 and the plugin stopped listing the folders for me.

@cronoklee  ftp is not part of atom cause atom is a text editor, not a development ide, nor a development ide for web project specifically.

I used to work directly on ftp for bugs, then i understood that having a separate way to edit code and to deploy it is much better.

**Comment by icetee** [comment]
The new version has improved many bugs. But still contains bugs.
I'm happy to Pull Request, I close this issue.
