### ISSUE TITLE
Toggle Remote FTP tree is not working

### ISSUE THREAD

**Issue by med2k** [icetee/remote-ftp#1093]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/icetee/remote-ftp/issues

### Description

[When loading the configuration file in Atom and then trying to toggle the Remote FTP panel, it does nothing. I can connect to Remote FTP, I can do all the things, but I CAN'T use the Remote FTP pannel because it wouldn't show up.]

### Steps to Reproduce

1. [Load the .ftpconfig file in Atom]
2. [Click on Packages > Remote FTP > Toggle]
3. [It does nothing]

**Expected behavior:** [I expect to have the Remote FTP pannel with the Connect button and then have the tree view of my FTP server]

**Actual behavior:** [Nothing happens when clicking on Toggle]

**Reproduces how often:** [100% of the time]

### Versions

Remote FTP version: 2.1.2
Atom version: 1.23.1
MacOS High Sierra version: 10.13.2

### Additional Information

FTP config file is for SFTP connection

**Comment by icetee** [comment]
The old panel method no longer applies the plugin. Since Atom v1.17 available [Dock logic](http://blog.atom.io/2017/04/12/atom-1-16.html). You may not have used it yet or you can use a custom theme to hide dock panes.

Maybe related https://github.com/icetee/remote-ftp/issues/1081

I'll end this issue, if there is a problem, I'll open it.

**Comment by felixholub** [comment]
Indeed, it was a problem with a theme as discusses here: https://github.com/icetee/remote-ftp/issues/1081
