### ISSUE TITLE
Horizontal scroll does not work

### ISSUE THREAD

**Issue by wstudios** [icetee/remote-ftp#158]
I have many folders level on my server but i am unable to use the scroll bar to view them, it just does not move. When I place my mouse over the horizontal bar it changes to an up arrow and/or clicking on the bar to slide does nothing.

**Comment by jpxd** [comment]
Which OS are you using? On Mac OS you can use the trackpad to scroll horizontally.
The problem is because of the log panel under the tree view which you can resize vertically. Because the scollbar is very thin, your cursor easily hits the _resize zone_ for the log panel. Try to move your curser up just a little bit...

**Comment by wasikuss** [comment]
Use `SHIFT+MOUSE_SCROLL` :) Works on Windows.

**Comment by wstudios** [comment]
Thanks for the reply, I am using Yosemite. i tried moving the cursor up slightly but it only changes from the (up) resize arrow to the normal select cursor and when clicked, selects the folder inside the tree and not the scrollbar. To see the rest of the folders, I have to resize the panel horizontally, which is fine to do.
