### ISSUE TITLE
Find/replace replaces on local copy not remote and requires manual save to upload

### ISSUE THREAD

**Issue by ghost** [icetee/remote-ftp#168]
On one and multiple files. If find/replacing 100 files this becomes an issue.

**Comment by jimmaaay** [comment]
I know this is a year old issue, but for anyone else who may have this problem it may be of use. 

Due to how the plugin is currently implemented something like this doesn't seem very feasible to do. What could be done however is to either do a local to remote sync, or watch the files / folders which will be changed or even the root of the project, with the `watch` option in the ftpconfig file.
