### ISSUE TITLE
Feature (self)request: validate .ftpconfig

### ISSUE THREAD

**Issue by wasikuss** [icetee/remote-ftp#175]
Hi, what do you think about create small module to validate .ftpconfig? I saw many issues like

> Uncaught Parse error in ...

`Validate Module` could check and display errors more verbosely ( show line, and mark error ) or even check scheme ( required, field types) if JSON object is valid.

I can do this module myself. I only want to know your opinions.

**Comment by jpxd** [comment]
Yeah, I closed the old ones and removed the 'Create issue' button from the error message, since it's not the package's fault (see c0172005c57bf133dc8c17eb1292dbe0df3fd666)
Would be nice to show the line number and the token where the parse error occurred...
What do you mean by creating a 'small module' ? I'm sure [jsonlint](https://github.com/zaach/jsonlint) would do the job...

**Comment by wasikuss** [comment]
Small module ( another js file ) was good solution to separate validation JSON syntax and schema from client.js  But it would be useless and waste of time, due to next feature ( config manager with UI ).
