### ISSUE TITLE
Multiple remote FTP servers. How could I do it per projects?

### ISSUE THREAD

**Issue by ghost** [icetee/remote-ftp#205]
Doesn't seem to work. Every time I create a new project and try to add a new config file, it overwrites the main one.

**Comment by shogerr** [comment]
Use a different directory, locally to start atom, then define the config file.

**Comment by ghost** [comment]
So basically, you are telling me that it is possible to have multiple FTP servers? All I have to do is have a .ftpconfig file for each project folder?

Since I work on many projects, I want to be able to have a distinct .ftpconfig file for each project folder...

**Comment by shogerr** [comment]
Yes. By placing a ftpconfig inside of a folder it will become the working directory for that site. So then you can just open atom in that folder as a project and it will have the ftp for that project ready to go.

**Comment by philipvollet** [comment]
but what if I have more than one project open in atom? I have the issue that if I work in another project file and save there the data (no ftpconfig file is placed in this projectfolder) the plugin upload my work of this project through the ftp directory of the first opend project dir with config file? Is this a bug or a normal behaviour?

**Comment by JamesCoyle** [comment]
I too have issue with the way it is implemented (I was about to create a similar issue just now). I often have multiple project folders open in atom. When I save a file in a project folder that **isn't** the site project folder it is uploaded anyway and I have to go back and delete the files from the server. There are several similar issues I have too where files are misplaced or not downloaded or uploaded correctly.

I feel this plugin needs to operate differently in order to be more user friendly. I have many ideas for improvements to the interface and operation and can talk about this in much more detail but do not have time to do so now as I soon have lectures. I may update this issue later to share my thoughts on this project but you can feel free to ask me to do so should I forget.

**Comment by Sjerd** [comment]
you can open the projects in different windows and it will work fine.

**Comment by shogerr** [comment]
Yeah, atom is designed to have one window open per folder/project. Does Sjerd's suggestion work for everyone? one window = one project folder = one remote ftp config

**Comment by ghost** [comment]
For my workflow, I dislike having to switch between windows. It would be handy to have the Remote-FTP connect to the active project (how this is determined is debatable...perhaps by what project/folder is selected).

**Comment by heroselohim** [comment]
My suggestion. I have to agree with some users here that I would require to have multiple FTP proyects in one window. But... I don't require all of the connected at the same time. It would be enough to disconnect from the previous projects if I open another folder project or just when I choose to execute an FTP action on a different project/folder. It's unnecesary to have all of them connected.

**Comment by jpxd** [comment]
duplicate #122

**Comment by usmanibrahim74** [comment]
> Yes. By placing a ftpconfig inside of a folder it will become the working directory for that site. So then you can just open atom in that folder as a project and it will have the ftp for that project ready to go.

you don't need to close that project folder and open new project folder

- open multiple project folders in atom and add ftpconfig file in each folder
- now drag the folder you want to work on to top in atom and connect via remote ftp

you ready to go

![image](https://user-images.githubusercontent.com/20674784/54868428-35933980-4dae-11e9-8c5b-41da931e3c28.png)
