### ISSUE TITLE
Why is a local project needed?

### ISSUE THREAD

**Issue by janstieler** [icetee/remote-ftp#369]
Hi,
why is it necessary to have an local project to use remote-ftp?
There a several project I'm working on and for they I don't want to have an local copy on my harddisc.
It would be nice if I could use this extension without an local project.

What also would be nice, would be a drag and drop function to upload folder and files to the ftp-folder.

Cheers

**Comment by robbertstevens** [comment]
I dont want all my projects locally either. would be a good addition

**Comment by hatzopoulos** [comment]
> why is it necessary to have an local project to use remote-ftp?

This is just the way the package has been designed. [There are other packages](https://atom.io/packages/search?utf8=%E2%9C%93&q=ftp) that might suit your workflow style better.  And if it's any consolation, you can open multiple Atom instances each with their own project. Although I can understand the desire to keep your local disk clean of these files you don't need.

There are also ways to use atom with other apps to achieve the workflow you desire. For example winSCP can be [configured](https://winscp.net/eng/docs/task_edit) in such a way so that when you open remote files they open in atom and saving changes are automatically uploaded. Yet another is to use something like [transmit](https://panic.com/transmit/). In this sense you do not need this package at all.

That being said, it would be cool if this project also supported a 'remote explore' type feature that allowed one to have a list of server instances, connect to multiple of them and able to navigate their remote trees all in one panel. Then every time you opened a remote file it would create a temporary local file for editing purposes but on every Save would upload back to the remote.
