### ISSUE TITLE
How to connect using PEM file

### ISSUE THREAD

**Issue by shahidkarimi** [icetee/remote-ftp#375]
Package works fine. What about sftp connection using .pem/ppk from windows?

**Comment by QinMing** [comment]
It works well on my Windows laptop. I'll paste my config file here for your reference.

``` json
{
    "protocol": "sftp",
    "host": "ec2-xxxxx.compute.amazonaws.com",
    "port": 22, 
    "user": "ec2-user", 
    "pass": "",
    "promptForPass": false, 
    "remote": "/home/ec2-user/git",
    "agent": "pageant", 
    "privatekey": "C:/Program Files Green/YourKey.pem",  //Using '/' is fine
    "passphrase": "", 
    "hosthash": "sha1",  //it just works
    "ignorehost": true,
    "connTimeout": 10000,
    "keepalive": 58000, 
    "watch":[]  //Caution: the sample config file they provide has value in this field. Make sure to clear it or you will get an weird error.
}
```

This is saved in `D:\git\.ftpconfig` on my computer, and I set `~/git` as the root directory on remote machine. Every time I just open Atom in `D:\git` and connect my server. Some temp files will be downloaded in the local machine. The folders are named `git` on both sides so that it's more convenient.

**Comment by jimmaaay** [comment]
Gonna close this, if you still having any issues leave a comment and I'll re open it.
