### ISSUE TITLE
SFTP doesn't work with PORT other than 22

### ISSUE THREAD

**Issue by gymbo97** [icetee/remote-ftp#395]
I tried to reach my remote server via port 50406 but I get the error:

 Remote FTP: Error: All configured authentication methods failed

the Settings:
{
    "protocol": "sftp",
    "host": "MyIP.co",
    "port": 50406,
    "user": "user",
    "pass": "pass",
    "promptForPass": false,
    "remote": "/",
    "agent": "",
    "privatekey": "/Users/MyUser/.ssh/id_rsa",
    "passphrase": "MyPassphrase",
    "hosthash": "",
    "ignorehost": true,
    "connTimeout": 10000,
    "keepalive": 10000,
    "keyboardInteractive": false,
    "watch": []
}

tried also with keyboardInteractive set to true still doesn't work

**Comment by jimmaaay** [comment]
Can you connect to your server on a different ftp client like filezilla with that port?

**Comment by hatzopoulos** [comment]
@gymbo97,

There's something wrong with your authentication setup since you're getting [`All configured authentication methods failed`](https://github.com/mscdex/ssh2/blob/b62b5430ebde1bb135297e08426cd073abc684da/lib/client.js#L377). It's strange to me that you're using a `"pass"` when you are already using a `privatekey` and `passphrase`, could it be that you don't need the `pass`?

Having the wrong port would give you a different error: [`Timed out while waiting for handshake`](https://github.com/mscdex/ssh2/blob/b62b5430ebde1bb135297e08426cd073abc684da/lib/client.js#L671)

**Comment by maronai** [comment]
I observed the same issue, ssh works on whatever port but my sftp does not after dist-upgrade.
