### ISSUE TITLE
Remote FTP still active after closing project folder

### ISSUE THREAD

**Issue by Evandar276** [icetee/remote-ftp#428]
I closed project folder with .ftpconfig and open another folder. When I opened and saved file to new folder, FTP connection restarted itself and uploaded file into FTP folder. I had to restart Atom to get rid of ftp. Thanks

**Comment by andrrrl** [comment]
I have the same issue. This package is real nice, real fast, etc, but this issue is v-e-r-y annoying. 
I have many projects added to my navigation panel, but I can't seem to add 1 config file per project, it's like you can have 1 project at a time only, and can't close and continue with another without restarting Atom or disabling the package.

**Comment by jimmaaay** [comment]
If you're using multiple projects with remote ftp, you will probably need to open them in separate windows. This a known issue and hope to find a fix for this at some point.

**Comment by Evandar276** [comment]
yes, I find out that opening second project folder in separate window works
:)

út 13. 9. 2016 v 17:55 odesílatel jimmaaay notifications@github.com
napsal:

**Comment by jpxd** [comment]
What @jimmaaay said. Only one project folder per window is recommended with Remote-FTP
