### ISSUE TITLE
Warn on download if local files newer than hosted

### ISSUE THREAD

**Issue by JamesCoyle** [icetee/remote-ftp#450]
Ask the user if they want to overwrite the local file when downloading the file from the server if the local file is newer than (updated after) the one on the server.

**Comment by jimmaaay** [comment]
@JamesCoyle I've been investigating the possibilities with this, and was thinking instead of a prompt have it so when someone opens the local copy a bar could show at the bottom of the editor and show the last modified date of the local and the server copy. It'd be great to hear your thoughts on this.

**Comment by JamesCoyle** [comment]
Any implementation that prevents you from overwriting a file either on the server or local machine that is newer than the one it will be overwritten with is fine for me. Ideally it would open both files side by side with the differences highlighted so you can choose which one to use.

**Comment by havok89** [comment]
+1 for this, was just coming to suggest it. Have previously been using dreamweaver so have been used to it prompting when uploading or downloading a file if it has been modified elsewhere).

As above any implementation would be good so long as it prevents the upload or download from happening until you have confirmed/compared the changes.

A bar at the bottom of the screen would need to be noticable so that if you are just making a quick change your not going to miss it and overwrite something, I think some kind of prompt would be the best way.

**Comment by jpxd** [comment]
Should be implemented for both directions (local file newer or remote newer) possibly with an option in the package settings to disable the warning.

**Comment by jpxd** [comment]
Duplicate to #132
