### ISSUE TITLE
Remote-FTP uploads/downloads files/folders

### ISSUE THREAD

**Issue by kartagis** [icetee/remote-ftp#584]
From time to time, I see remote files/folders downloaded to my local project folder, or local files/folders uploaded to the remote folder. I don't think this is desired.

![screenshot 2016-11-21 11 43 47](https://cloud.githubusercontent.com/assets/1607518/20476165/2d65cc3a-afd8-11e6-86d6-7c4ea98dd52d.png)

The folders annotated are supposed to be only on the local folder, and drupal-7 in the local folder only in the remote folder.

**Comment by htho** [comment]
Since I added an .ftpignore file to *each* project folder I have this issue less often.

My .ftpconfig ignores all files. I only want to edit remotefiles.  They should be uploaded after I save them.

.ftpignore
```
!**
```

Additionally I have a single local file that is watched and uploaded if it changes. That works fine in combination with my .ftpignore.

**Comment by jpxd** [comment]
Nice idea @htho!
