### ISSUE TITLE
Remote delete should also delete local file

### ISSUE THREAD

**Issue by ol1s** [icetee/remote-ftp#614]
When I am browsing the remote FTP and delete a file on the server, it would be really handy if this also deleted the local version. That way it keeps the project directory organised and means that I can commit deletes to version control without missing them accidentally.

**Comment by jpxd** [comment]
Hmm this sounds like a dangerous thing to do if this behavior not expected by some users... Maybe a prompt asking for "Do you want to delete the local file too?". Or is this too disruptive for the workflow? But just deleting without asking would be bad.
Feel free to submit a PR :)

**Comment by Wombosvideo** [comment]
I think this should be added both-side and the prompt should be disableable in the project-specific .ftpconfig

both-side means when you delete a local file, it is also deleted on the server and if you delete a file on the server, it is also deleted locally

**Comment by jpxd** [comment]
Hmm I agree, an option would be good, but I'd prefer it in the global package settings because I don't want to clutter the .ftpconfig file with too many options...

Do you think just two package settings ("Delete local file when deleting remote", "Delete remote file when deleting local") (which are both false as default) without extra prompts when deleting something are sufficient?

**Comment by Wombosvideo** [comment]
I think so
