### ISSUE TITLE
Remote Directory to user home directory

### ISSUE THREAD

**Issue by streamworksaudio** [icetee/remote-ftp#622]
Is it not possible to get the Remote Directory to go to the user's home directory?  

From the config file, I am only able to go to that directory (when logging in) if I use and absolute path.  Is it not possible to just use something like "/~" for the remote directory?

Cheers

**Comment by agm1984** [comment]
I'm not sure what you mean exactly, but try investigating something like this:
http://askubuntu.com/questions/33421/give-ftp-users-access-to-directories-outside-their-root-using-symlinks

**Comment by streamworksaudio** [comment]
Thanks for the reply.  I do not think that is the problem however.  

When I connect to our ftp server with any client (Filezilla, or even ftp thru OS X terminal), when logging in with a user specific credentials I am taking to that users home directory.  

However with the same user credentials setup in the config file for remote-ftp, I am taking to the servers's root directory every time.

**Comment by agm1984** [comment]
hmm, check your ftpd config file and see if you can force the directory.

If its just for one user, it will work.

I use vsftpd on fedora25 and if i set the directory in /etc/vsftpd/vsftpd.conf to /srv/www/, then i can use the ftp with my user creds.

So I guess my recommendation is to find a config file and change the default directory on the ftp to your desired one. I just noticed I am using the correct server folder in my remote-ftp config: 

"remote": "/srv/www/"

You might start running into user permission issues due to the webserver running off a different username than your ftp user. If you get that, research directory ACLs (setfacl and "getfacl /folder/area/"). Create a group and set ownership of the directory to the group, and then add all affected users to the group.

Just make sure you have read/execute but not write priv in your web server directory. Sorry I just blasted you with a bunch of stuff there, but its relevant to get your ftp setup to run with the web server depending on what you are trying to do exactly. I recommend making a stackoverflow post about it. Someone will get you dialed in pretty quick.

-Adam

**Comment by streamworksaudio** [comment]
Hi again Adam,

I am also using vsftpd on Ubuntu 14.04 and with the current config it takes a logged in user to their home directory (at least it does when I login with other ftp clients).  

While I am able to enter an absolute path in the remote-ftp config file ("remote":"/path") I thought that maybe there was something I was missing to make remote-ftp go to to the user's default dir.  I am guessing that the remote: value is sent as a CD command to take you to the path in the remote-ftp config.

Don't worry about blasting me... I am following you ;)

**Comment by agm1984** [comment]
Nice, ok, lemme see.

On your box, edit /etc/vsftpd/vsftpd.conf

Find:
`local_root=/foo/bar`

if local_root isn't there, just add it. Set it to your desired directory. There might be some other options you need as well, so play with the settings and config file. I'm using that method with "/" as the directory in remote-ftp config file.

**Comment by streamworksaudio** [comment]
Thanks again,

local_root is not defined in the config file.  I could enter that there, but in that case I think it would be easier, and makes more sense, to set the directory in the remote-ftp config.

I am still curious as to why all other clients take me to the home directory (even Code Anywhere) of the logged in user, but remote-ftp does not.  It is not a show stopper (as I can hard code the dir. I want to go to in the remote-ftp config file), I am just interested in the 'why' more than the 'how to'.

Cheers

**Comment by agm1984** [comment]
Mine wasn't in the config file either when I first edited mine. I added it.

Consider that your server is routing logged in users to probably /home/{{user}} by default. That is where it is hosting the FTP. Remote-FTP is simply connecting to your FTP, so putting "/" in the config probably drops them in the root which is defined by your system (home dir by default).

Consider the security ramifications of defining a folder like /etc in your remote-FTP config :) You could probably travel out of the FTP root directory if your user had permission to, but it's not trending in a good direction security-wise.

I'm looking at my VSFTPD config again now and it looks like the only thing I changed was appending:

`local_root=/srv/www`

Try it real quick and just peel it back if it doesn't work. If it's just your user using the FTP, you should be fine.

It's not that Remote-FTP isn't letting you do it. It's that VSFTPD isn't serving that directory. That's my current opinion anyway lol. Check this link out. Sounds confusing AF but the keywords in here should lead you to victory if you need to configure the FTP for multiple users in different directories: http://howto.gumph.org/content/setup-virtual-users-and-directories-in-vsftpd/

-Adam

**Comment by agm1984** [comment]
I just changed my config to "/etc" to see what happens, and it doesn't seem to do anything. You might be right there is a bug there.

Mine goes to /srv/www and im certain its because local_root=/srv/www in vsftpd config.

I just noticed I can browse the whole filesystem if I connect to the FTP in an FTP client, so my vsftpd is wack. I need to prevent user from navigating outside the serving directory.

I'm looking into my issue now. You might find this helpful:
http://www.ducea.com/2006/07/27/allowing-ftp-access-to-files-outside-the-home-directory-chroot/

**Comment by agm1984** [comment]
Check this out also if you are the only person using your FTP service:
http://serverfault.com/questions/577393/vsftpd-limit-connection-to-a-set-of-ip-addresses

My box is locked down, but I realized my FTP was totally insecure, so I locked it down to my IP only. Worked perfect. 

Put `tcp_wrapper=yes`, then add `vsftpd: all` to /etc/hosts.deny and then connect to your FTP. it should fail. then add your IP, `vsftpd: {{ip}}` to /etc/hosts.allow and it will work. It's a good security measure just in case anyone were ever to gain access to your FTP. My box, for example, is locked down to only one user via SSH requiring key, but my FTP would have still permitted them to browse my whole file system.

**Comment by streamworksaudio** [comment]
Actually.... it might be because I have my vsftpd setup so that the user can CD up out of their home dir.  So perhaps remote-ftp is actually send a CD command (for example /), and because the user is allowed to go to there it does.  This would make sense.

I could lock down the user to only going to the home dir.  But is some cases this user needs access to dir. outside it's home.   Maybe locking it to my IP (as I did with some site for Apache) is a good idea.

**Comment by agm1984** [comment]
Oops, I thought I posted this one last night: http://www.ducea.com/2006/07/27/allowing-ftp-access-to-files-outside-the-home-directory-chroot/

You can basically mount the directory so your user can access it like a symlink.

But, anyway, I would definitely lock it down to your IP only. You never know those crazy MFers out there.

I was trying to enable chroot on mine last night but my FTPD is serving /srv/www so it was giving error 500, so I just locked it to my IP instead. Close enough.gif

**Comment by samifouad** [comment]
Going to close this as a dupe/related to #80
