### ISSUE TITLE
Add support for git-diff

### ISSUE THREAD

**Issue by Wombosvideo** [icetee/remote-ftp#650]
**Feature request:**
Hey. I'd like to request an implementation of git-diff into the Remote-FTP Tree View because I really like how this packaged displays the new/removed/changed files in the default "Tree View". 

**Possible implementation:**
For me it would be enough to just display the same colors as in the "Tree View". This could however irritate some users as this way would not support external file-changes on the server. To prevent this, you could check for the "last-access" or "last-changed" or whatever this stuff's called server-side and check if it matches the local one (or do some md5 magic). And if  it does, display the local colors (same as "Tree View"). If it doesn't, you could display a little exclamation mark besides the file icon (when hovered, it says "File not in sync with local version")

[Atom.io git-diff Package](https://atom.io/packages/git-diff)

**Comment by melneff** [comment]
Any update on this?

**Comment by icetee** [comment]
There is a big problem that the date of the two files is not the same as even when saving. When saving, it will always be a new date. But when you up to the server, you get another date the same file.

Checksum it could still work, but somehow they should always be in sync. Not just when listing.

SFTP maybe it's okay, but simple FTP (HASH command) very small layer could use it. Even ProFTPD, just as a module.

Is there any idea for concrete implementation?

**Comment by mertyildiran** [comment]
@icetee I suggest publishing a modified version of [git-diff](https://github.com/atom/git-diff) with a name like `remote-ftp-git-diff`. 

`git-diff` package is not a complex package and modifying it for the purpose of using it with `remote-ftp` would not be so complicated. Changing a few lines like [this one](https://github.com/atom/git-diff/blob/master/lib/diff-list-view.js#L69), I believe will be enough. The modified version of `git-diff` should operate on the remote repository instead of the local repository. But showing `git-diff` result just on *Tree View* is **not enough** so it should also operate on the remote file(the file that the user is currently editing) instead of the local file to show `git-diff` result **in-line**.

Either @icetee you or I can modify `git-diff` and publish such a package but as far as I'm concerned; it will be a difficult task for me while for you @icetee it would be much easier to develop that package. (or maybe some other contributor can do it easily)

I desperately need `git-diff` feature for my personal use so @icetee please let me know if you will do it. Otherwise, please at least help me and answer my future questions about your `remote-ftp` package while I will be doing this(modifying [git-diff](https://github.com/atom/git-diff)) challenging - for me - task.

**Comment by Wombosvideo** [comment]
This issue was closed due to abandonment of Atom
