### ISSUE TITLE
Configure active mode ftp connection

### ISSUE THREAD

**Issue by billy722** [icetee/remote-ftp#683]
Whe I try to connect to my hosting with filezilla I have to set the transfer mode  in "active", but I don't know how to do it in remote ftp.
(If I don't set it in active mode, I receive an error when it tries to listing directory).

**Comment by samifouad** [comment]
Just curious, are you sure you don't mean "passive"?

Usually it's active mode that gives people problems when listing directories so most clients, servers and connection libraries default to passive.

I'm not sure what the default for this plugin is but I'll take a look and post. Also, if you use SFTP, this issue doesn't apply. Is using SFTP instead of FTP an option for you?

**Comment by samifouad** [comment]
This plugin utilizes node's ftp package. And that package does not support active mode.

See: https://github.com/mgrenier/remote-ftp/issues/239#issuecomment-163369829

**Comment by billy722** [comment]
Hi, thanks a lot for your answer. Finally I asked my hosting provider to allow me to connect in passive mode using ftp, and they do it. Anyway thanks for your time.
