### ISSUE TITLE
No upload on save if not already connected

### ISSUE THREAD

**Issue by HappyZone** [icetee/remote-ftp#742]
Since a few builds, saving a file won't connect automagically to the remote host and save the edited file, you need to manually connect first.

"Before", whenever I would open an existing project (with existing .ftpconfig), working on any file and saving it would connect to the remote host and save the file.

Tested on v0.10.7

**Comment by sorinpohontu** [comment]
Confirmed on same version. No visible errors in Console.
If I Connect, it's working as expected.

**Comment by bkonia** [comment]
Same issue here

**Comment by ghost** [comment]
Issue? This __IS__ the correct behaviour! How would you save to a local file without accidentally moving it to your FTP-Server too?

**Comment by bkonia** [comment]
@icetee, we can all do without your arrogant and condescending response, particularly since you seem to be clueless about this issue and YES it **IS** an issue.

No idea what you're talking about, with respect to "accidentally" moving it to your FTP server. If a site is configured to automatically upload saved files, there would be nothing "accidental" about it. The point is, if you lose your FTP connection, it should automatically reconnect. Not sure why this is such a bizarre concept to you???

**Comment by robhuska** [comment]
@bkonia I don't believe he was being arrogant, maybe a miss understanding of the bug? Either way the guy has voluntarily taken the reasonability to maintain this package that has needed some serious attention for quite a while. Cut him some slack, he has gone through dozens of old threads trying to clean things up.

**Comment by icetee** [comment]
@bkonia what did I write?

I remove duplicate issues. When very first connected not lucky upload file. (May bad path, etc.)
It is planned to "auto-reconnect" function, if lose connection, timeout etc.

**Comment by robhuska** [comment]
@bkonia, actually the comment you are referring to was from anither user about a month ago, @xN118x. All @icetee did was close this issue because it was a duplicate of another.
