### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by kotko** [icetee/remote-ftp#909]
Atom 1.18.0 X64 (Sierra) Mac OS.
Not connect.
No file tree.
No toggle tree folder.

**Comment by Wombosvideo** [comment]
_see #907 or #839 for further discussion_
As far as it seems, this issue only appears for **certain people** and mostly on **Mac OS**. I haven't tested the plugin fully but the file tree is working, connecting works too but since I have zero files on my server yet I can't say whether it works. 
I am running Atom 1.18.0 ia32 on Windows 10 x64

**Comment by jan-vince** [comment]
I just can confirm, that with same configuration (Atom 1.18.0 x64, MacOS Sierra, remote-ftp 1.1.3) all works for me.

**Comment by isherwood** [comment]
I'm on Windows 10/64 and Remote-FTP quit connecting today. It simply returns 

> Remote FTP: Connection closed

Is this the same issue?

**Comment by sangdth** [comment]
Same with kotko. No file tree. No toggle. No configure. No preferrence. No reaction with shortcut. Nothing.

**Comment by EvanHerman** [comment]
Same issue here - the plugin stopped functioning. 

Mac OSX Sierra v10.12.5
Atom v1.18.0 x64
Remote FTP 1.1.3

**Comment by EvanHerman** [comment]
Resolved with help from https://github.com/icetee/remote-ftp/issues/839
