### ISSUE TITLE
Seemingly random "Upload Error Failure"

### ISSUE THREAD

**Issue by dannymcgee** [icetee/remote-ftp#942]
I've just recently started getting "Upload Error Failure" notifications when trying to upload files via Remote FTP. The issue doesn't occur every time, and I've been unable to find steps to reproduce it consistently. It occurs both with right-click > Upload and right-click > Sync local -> remote.

Console logged the following error once, but other times the console has been quiet:

Error: Failure(...)
(anonymous function) @ commands.js:422

Immediately after experiencing these errors, I switched to FileZilla to do my uploading tasks and it worked without any problems, which leads me to believe the issue is specific to Remote FTP.

**Comment by Dopey117** [comment]
I believe you are experiencing the same thing I am. If the file you are working on is inside a collapsed folder on your local tree, the file will fail to upload.

Steps to reproduce:
1. Collapse your local project folder
2. Double click file on server to download and open
3. Try to upload it. Upload failed.

**Slight change in v1.2 release, error message now reads "no such file" instead of generic upload failed message. And after failed upload the uploader gets stuck and will not allow you to download or upload anything until you restart Atom or disconnect/reconnect.

**Workaround**: Make sure ALL of your local folders are expanded and make sure that the file you are trying to upload is highlighted in your local view

**Comment by danielhickman** [comment]
I believe @Dopey117 is right, however, it's fairly impossible to have all of my bower_components expanded, especially if a new one is added from a build if I'm building locally.

**Comment by Dopey117** [comment]
I know I said ALL your folders, but really as long as you make sure to expand the ones you are actively working in you will be fine.  As long as the file you want to upload is highlighted in your local view it will upload

**Comment by icetee** [comment]
Resolve, if there is a problem then I will reopen.
